spring:
  application:
    name: server
  mustache:
    suffix: .html
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  session:
    jdbc:
      initialize-schema: always

  security:
    user:
      name: user
      password: password
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        globally_quoted_identifiers: true

jwt:
  secret: "Hola"
  exptime: 1296000000